# Generated by Django 3.2.4 on 2021-07-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonedaPago',
            fields=[
                ('idMonedaPago', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Moneda de Pago')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Tipo Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorNuevo',
            fields=[
                ('nroIdentificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número Identificación')),
                ('fotoLogo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre Completo')),
                ('fono', models.IntegerField(verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('contraseña', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('monedaPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundzero.monedapago')),
            ],
        ),
    ]
