# Generated by Django 3.2.4 on 2021-07-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundzero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedornuevo',
            name='fotoLogo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
