# Generated by Django 3.2.4 on 2021-07-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundzero', '0002_alter_proveedornuevo_fotologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedornuevo',
            name='fotoLogo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
